services:
  - type: web
    name: khojbazaar
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn khojbazaar.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: khojbazaar-db
          property: connectionString

databases:
  - name: khojbazaar-db
    databaseName: khojbazaar
    user: khojbazaar_user
    plan: free
