services:
  - type: web
    name: khojbazaar
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn khojbazaar.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
