# Generated by Django 6.1 on 2026-09-10 11:46

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('favicon', models.ImageField(upload_to='static/uploads/')),
                ('logo', models.ImageField(upload_to='static/uploads/')),
                ('bio', django_ckeditor_5.fields.CKEditor5Field()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(10)])),
                ('fb_link', models.URLField(blank=True)),
                ('insta_link', models.URLField(blank=True)),
            ],
        ),
    ]
